# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "40bd821ed8be807837fc09447f5ae188"
name = "Delivery Date Picker"
handle = "delivery-date-picker-66"
application_url = "https://flame-supreme-gradually-opening.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "lumenshopbd.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://flame-supreme-gradually-opening.trycloudflare.com/auth/callback",
  "https://flame-supreme-gradually-opening.trycloudflare.com/auth/shopify/callback",
  "https://flame-supreme-gradually-opening.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
